/**
 * Function schema types for RayfinClient.
 *
 * Pass this as the third type parameter of `RayfinClient` so that
 * `client.functions.askDataAgent.invoke(...)` is type-checked. Regenerated by
 * `rayfin dev functions apply` whenever `udf.func()` registrations change.
 *
 * IMPORTANT: This file must NOT import any Node.js packages — it is resolved
 * by the frontend app's TypeScript compiler.
 */

export type AppFunctionsSchema = {
  askDataAgent: {
    input: { question: string; threadId?: string };
    output: { answer: string; threadId?: string; toolName?: string; durationMs?: number };
  };
};
