import { getRayfinClient } from '@/services/rayfinClient';

import { looksDeclined } from './ProxyAgentService';
import type { AgentAnswer, AgentService, AskOptions } from './types';

/** The output shape of `askDataAgent` in `rayfin/functions/src/function_app.ts`. */
interface AskDataAgentOutput {
  answer: string;
  threadId?: string;
  toolName?: string;
  durationMs?: number;
}

/**
 * The in-estate path: a Rayfin function calls the Data Agent's MCP endpoint
 * server-side, under a service principal whose secret lives in
 * `rayfin/.env.secrets`, never in the browser.
 *
 * Rayfin functions are experimental in 1.34 and are not enabled on every
 * tenant, so this backend is opt-in (`VITE_AGENT_MODE=function`) and the
 * proxy path is the rehearsed one.
 */
export class FunctionAgentService implements AgentService {
  readonly mode = 'function' as const;
  readonly description =
    'Fabric Data Agent, called from a Rayfin function inside the workspace. The service principal’s permissions apply, not the signed-in clinician’s.';

  readonly suggestedQuestions = [
    'Which of my pre-operative patients are flagged, and why?',
    'Which factors contributed most for this patient?',
    'How does our flag rate compare with other providers?',
    'What happens to the flagged count at a threshold of 0.7?',
  ] as const;

  async ask(question: string, options: AskOptions = {}): Promise<AgentAnswer> {
    const started = performance.now();
    const id = `ans-${Date.now()}-${Math.floor(Math.random() * 1e6)}`;
    try {
      // The functions schema is generated by `rayfin dev functions apply`; the
      // client is typed loosely here so the frontend compiles before it runs.
      const functions = getRayfinClient().functions as unknown as {
        askDataAgent: {
          invoke: (params: { question: string; threadId?: string }) => Promise<AskDataAgentOutput>;
        };
      };
      const out = await functions.askDataAgent.invoke({ question, threadId: options.threadId });
      return {
        id,
        question,
        status: looksDeclined(out.answer) ? 'declined' : 'answered',
        text: out.answer,
        groundedOn: ['Fabric Data Agent'],
        citations: [],
        latencyMs: Math.round(performance.now() - started),
        source: this.mode,
        threadId: out.threadId ?? options.threadId,
      };
    } catch (err) {
      return {
        id,
        question,
        status: 'error',
        text: err instanceof Error ? err.message : 'The function could not be invoked.',
        groundedOn: [],
        citations: [],
        latencyMs: Math.round(performance.now() - started),
        source: this.mode,
        threadId: options.threadId,
      };
    }
  }
}
