import { chromium } from 'playwright-core';
const out = process.argv[2]; const base = process.argv[3] || 'http://localhost:5199';
const exe = '/Users/sarasaudrius/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing';
const browser = await chromium.launch({ headless: true, executablePath: exe });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2, colorScheme: 'light' });
const page = await ctx.newPage();
page.on('pageerror', e => console.log('PAGEERROR', e.message));
await page.goto(base + '/', { waitUntil: 'networkidle' });
await page.evaluate(() => localStorage.setItem('mf-theme', 'light'));
await page.reload({ waitUntil: 'networkidle' });
await page.screenshot({ path: `${out}/auth.png`, fullPage: true });
const btn = page.getByRole('button', { name: /Continue to the offline|Sign in/ });
await btn.first().click(); await page.waitForTimeout(1200);
const shot = async (name) => { await page.waitForTimeout(1000); await page.screenshot({ path: `${out}/${name}.png`, fullPage: true }); console.log('shot', name); };
await shot('home');
await page.click('nav[aria-label="Primary"] a[href="/worklist"]'); await shot('worklist');
await page.click('nav[aria-label="Primary"] a[href="/ask"]'); await shot('ask');
await page.click('nav[aria-label="Primary"] a[href="/model"]'); await shot('model');
await page.click('nav[aria-label="Primary"] a[href="/worklist"]'); await page.waitForTimeout(800);
await page.locator('a[href^="/patient/"]').first().click(); await shot('patient');
await browser.close();
